CREATE TABLE SPECIES
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    LANGUAGE VARCHAR(255),
    NAME     VARCHAR(255) UNIQUE
);

CREATE TABLE FILM
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    DIRECTOR     VARCHAR(255),
    RELEASE_DATE DATE,
    TITLE        VARCHAR(255) UNIQUE 
);

CREATE TABLE PERSON
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(255) UNIQUE ,
    GENDER     VARCHAR(255),
    SPECIES_ID BIGINT,
    FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES (ID)
);

CREATE TABLE PERSON_FILM
(
    PERSON_ID BIGINT NOT NULL,
    FILM_ID   BIGINT NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
    FOREIGN KEY (FILM_ID) REFERENCES FILM (ID)
);
